services:
  postgres:
    image: postgres:15-alpine
    container_name: lothrop-postgres
    environment:
      POSTGRES_DB: lothrop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: lothrop-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POSTGRES_DB=lothrop_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./backend:/app
      - /app/tmp
      - backend_modules:/go/pkg/mod
    depends_on:
      postgres:
        condition: service_healthy
    command: ["air", "-c", ".air.toml"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: lothrop-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_modules:
